version: '3.8'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: ramen_asmr_development
      MYSQL_USER: ramen_asmr
      MYSQL_PASSWORD: database_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0' -p 3000
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
      selenium:
        condition: service_started
    environment:
      DATABASE_USERNAME: ramen_asmr
      DATABASE_PASSWORD: database_password
      DATABASE_HOST: db
      SELENIUM_DRIVER_URL: http://selenium:4444
      CAPYBARA_SERVER_HOST: 0.0.0.0
      CAPYBARA_APP_HOST: http://web:3000
  selenium:
    image: seleniarm/standalone-chromium:4.17.0
    ports:
      - "4444:4444"

volumes:
  mysql-data: