default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: ci_password
  host: mysql
  port: 3306

development:
  <<: *default
  database: ramen_asmr_app_development

test:
  <<: *default
  database: ramen_asmr_app_test

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_URL'] %>
  pool: 5
