default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: ramen_asmr
  password: database_password
  host: db
  port: 3306

development:
  <<: *default
  database: ramen_asmr_development

test:
  <<: *default
  database: ramen_asmr_test

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_URL'] %>
  pool: 5
