// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "videos"
import "search_form"
import "my_page"
import "map"
import "location_information"
import "comments"
import "avatar_preview"
import "autocomplete"
import "top_page"
