mailer:
  smtp_settings:
    address: smtp.zoho.jp
    port: 587
    domain: ramen-sounds.com
    user_name: info@ramen-sounds.com
    password: !ENV 'SMTP_PASSWORD'
    authentication: plain
    enable_starttls_auto: true