mailer:
  smtp_settings:
    address: "smtp.zoho.com"
    port: 587
    domain: "ramen-sounds.com"
    user_name: "info@ramen-sounds.com"
    password: "one5ok2rock4"
    authentication: "plain"
    enable_starttls_auto: true